# Главный исполняемый файл
main = "main.go"

# Собранный бинарник (Windows — exe)
bin = "tmp/main.exe"
# Если папки tmp нет — Air создаст её

# Перезапускать приложение сразу после пересборки
run_on_restart = true

# Для каких файлов следить за изменениями
[watch]
  # Следит за всеми .go файлами в internal и корне
  include = [
    "internal/**/*.go",
    "**/*.go"
  ]
  # Игнорировать скрытые и временные файлы
  exclude = [
    "tmp/",
    "node_modules/",
    ".git/",
    "**/*_test.go"
  ]

# Окружение для приложения (если нужно)
[env]
  PORT = 8081"

# Команда для сборки (можно и не указывать, если стандартная)
build = "go build -o tmp/main.exe ."

# Команда для запуска после сборки
cmd = "tmp/main.exe"
