version: "3.8"

tasks:
  help:
    desc: Display help for each task
    cmds:
      - echo "Usage:"
      - echo "  task <target>"
      - echo ""
      - task --list

  run:
    desc: swag run for API v1
    cmds:
      - go run main.go
