version: "3.8"

tasks:
  help:
    desc: Display help for each task
    cmds:
      - echo "Usage:"
      - echo "  task <target>"
      - echo ""
      - task --list

  run:
    desc: Run API Server
    cmds:
      - go run main.go -port 8081

  dev:
    cmds:
      - air
    desc: Run live reload with Air

  migrations:
    desc: Run Goose Migrations
    cmds:
      - goose -dir migrations postgres "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" up